WITH grouped AS (
  -- ALL
  SELECT Year,
    Region || '_ALL' Region,
    AVG(AACI) AS AACI
  FROM df_all
  GROUP BY 1,2

  UNION ALL
  -- CDD
  SELECT Year,
    Region || '_CDD' Region,
    AVG(AACI) AS AACI
  FROM df_cdd
  GROUP BY 1,2

  UNION ALL
  --RAINFALL
  SELECT Year,
    Region || '_RF' Region,
    AVG(AACI) AS AACI
  FROM df_rainfall
  GROUP BY 1,2

  UNION ALL
  --SEALEVEL
  SELECT Year,
    Region || '_SL' Region,
    AVG(AACI) AS AACI
  FROM df_sealevel
  GROUP BY 1,2

  UNION ALL
  --TEMPHIGH
  SELECT Year,
    Region || '_TH' Region,
    AVG(AACI) AS AACI
  FROM df_temphigh
  GROUP BY 1,2

  UNION ALL
  --TEMPLOW
  SELECT Year,
    Region || '_TL' Region,
    AVG(AACI) AS AACI
  FROM df_templow
  GROUP BY 1,2

  UNION ALL
  --WIND
  SELECT Year,
    Region || '_WI' Region,
    AVG(AACI) AS AACI
  FROM df_wind
  GROUP BY 1,2
), 
transposed AS (
  SELECT Year,
    --ALL
    CASE WHEN Region = 'AU_ALL' THEN AACI END AS AU_ALL,
    CASE WHEN Region = 'CS_ALL' THEN AACI END AS CS_ALL,
    CASE WHEN Region = 'EN_ALL' THEN AACI END AS EN_ALL,
    CASE WHEN Region = 'ES_ALL' THEN AACI END AS ES_ALL,
    CASE WHEN Region = 'MB_ALL' THEN AACI END AS MB_ALL,
    CASE WHEN Region = 'MN_ALL' THEN AACI END AS MN_ALL,
    CASE WHEN Region = 'RN_ALL' THEN AACI END AS RN_ALL,
    CASE WHEN Region = 'RS_ALL' THEN AACI END AS RS_ALL,
    CASE WHEN Region = 'SE_ALL' THEN AACI END AS SE_ALL,
    CASE WHEN Region = 'ST_ALL' THEN AACI END AS ST_ALL,
    CASE WHEN Region = 'SV_ALL' THEN AACI END AS SV_ALL,
    CASE WHEN Region = 'SW_ALL' THEN AACI END AS SW_ALL,
    CASE WHEN Region = 'WT_ALL' THEN AACI END AS WT_ALL,
    --CDD
    CASE WHEN Region = 'AU_CDD' THEN AACI END AS AU_CDD,
    CASE WHEN Region = 'CS_CDD' THEN AACI END AS CS_CDD,
    CASE WHEN Region = 'EN_CDD' THEN AACI END AS EN_CDD,
    CASE WHEN Region = 'ES_CDD' THEN AACI END AS ES_CDD,
    CASE WHEN Region = 'MB_CDD' THEN AACI END AS MB_CDD,
    CASE WHEN Region = 'MN_CDD' THEN AACI END AS MN_CDD,
    CASE WHEN Region = 'RN_CDD' THEN AACI END AS RN_CDD,
    CASE WHEN Region = 'RS_CDD' THEN AACI END AS RS_CDD,
    CASE WHEN Region = 'SE_CDD' THEN AACI END AS SE_CDD,
    CASE WHEN Region = 'ST_CDD' THEN AACI END AS ST_CDD,
    CASE WHEN Region = 'SV_CDD' THEN AACI END AS SV_CDD,
    CASE WHEN Region = 'SW_CDD' THEN AACI END AS SW_CDD,
    CASE WHEN Region = 'WT_CDD' THEN AACI END AS WT_CDD,
    --RAINFALL
    CASE WHEN Region = 'AU_RF' THEN AACI END AS AU_RF,
    CASE WHEN Region = 'CS_RF' THEN AACI END AS CS_RF,
    CASE WHEN Region = 'EN_RF' THEN AACI END AS EN_RF,
    CASE WHEN Region = 'ES_RF' THEN AACI END AS ES_RF,
    CASE WHEN Region = 'MB_RF' THEN AACI END AS MB_RF,
    CASE WHEN Region = 'MN_RF' THEN AACI END AS MN_RF,
    CASE WHEN Region = 'RN_RF' THEN AACI END AS RN_RF,
    CASE WHEN Region = 'RS_RF' THEN AACI END AS RS_RF,
    CASE WHEN Region = 'SE_RF' THEN AACI END AS SE_RF,
    CASE WHEN Region = 'ST_RF' THEN AACI END AS ST_RF,
    CASE WHEN Region = 'SV_RF' THEN AACI END AS SV_RF,
    CASE WHEN Region = 'SW_RF' THEN AACI END AS SW_RF,
    CASE WHEN Region = 'WT_RF' THEN AACI END AS WT_RF,
    --SEALEVEL
    CASE WHEN Region = 'AU_SL' THEN AACI END AS AU_SL,
    CASE WHEN Region = 'CS_SL' THEN AACI END AS CS_SL,
    CASE WHEN Region = 'EN_SL' THEN AACI END AS EN_SL,
    CASE WHEN Region = 'ES_SL' THEN AACI END AS ES_SL,
    CASE WHEN Region = 'MB_SL' THEN AACI END AS MB_SL,
    CASE WHEN Region = 'MN_SL' THEN AACI END AS MN_SL,
    CASE WHEN Region = 'RN_SL' THEN AACI END AS RN_SL,
    CASE WHEN Region = 'RS_SL' THEN AACI END AS RS_SL,
    CASE WHEN Region = 'SE_SL' THEN AACI END AS SE_SL,
    CASE WHEN Region = 'ST_SL' THEN AACI END AS ST_SL,
    CASE WHEN Region = 'SV_SL' THEN AACI END AS SV_SL,
    CASE WHEN Region = 'SW_SL' THEN AACI END AS SW_SL,
    CASE WHEN Region = 'WT_SL' THEN AACI END AS WT_SL,
    --TEMPHIGH
    CASE WHEN Region = 'AU_TH' THEN AACI END AS AU_TH,
    CASE WHEN Region = 'CS_TH' THEN AACI END AS CS_TH,
    CASE WHEN Region = 'EN_TH' THEN AACI END AS EN_TH,
    CASE WHEN Region = 'ES_TH' THEN AACI END AS ES_TH,
    CASE WHEN Region = 'MB_TH' THEN AACI END AS MB_TH,
    CASE WHEN Region = 'MN_TH' THEN AACI END AS MN_TH,
    CASE WHEN Region = 'RN_TH' THEN AACI END AS RN_TH,
    CASE WHEN Region = 'RS_TH' THEN AACI END AS RS_TH,
    CASE WHEN Region = 'SE_TH' THEN AACI END AS SE_TH,
    CASE WHEN Region = 'ST_TH' THEN AACI END AS ST_TH,
    CASE WHEN Region = 'SV_TH' THEN AACI END AS SV_TH,
    CASE WHEN Region = 'SW_TH' THEN AACI END AS SW_TH,
    CASE WHEN Region = 'WT_TH' THEN AACI END AS WT_TH,
    --TEMPLOW
    CASE WHEN Region = 'AU_TL' TLEN AACI END AS AU_TL,
    CASE WHEN Region = 'CS_TL' TLEN AACI END AS CS_TL,
    CASE WHEN Region = 'EN_TL' TLEN AACI END AS EN_TL,
    CASE WHEN Region = 'ES_TL' TLEN AACI END AS ES_TL,
    CASE WHEN Region = 'MB_TL' TLEN AACI END AS MB_TL,
    CASE WHEN Region = 'MN_TL' TLEN AACI END AS MN_TL,
    CASE WHEN Region = 'RN_TL' TLEN AACI END AS RN_TL,
    CASE WHEN Region = 'RS_TL' TLEN AACI END AS RS_TL,
    CASE WHEN Region = 'SE_TL' TLEN AACI END AS SE_TL,
    CASE WHEN Region = 'ST_TL' TLEN AACI END AS ST_TL,
    CASE WHEN Region = 'SV_TL' TLEN AACI END AS SV_TL,
    CASE WHEN Region = 'SW_TL' TLEN AACI END AS SW_TL,
    CASE WHEN Region = 'WT_TL' TLEN AACI END AS WT_TL,
    --WIND
    CASE WHEN Region = 'AU_WI' WIEN AACI END AS AU_WI,
    CASE WHEN Region = 'CS_WI' WIEN AACI END AS CS_WI,
    CASE WHEN Region = 'EN_WI' WIEN AACI END AS EN_WI,
    CASE WHEN Region = 'ES_WI' WIEN AACI END AS ES_WI,
    CASE WHEN Region = 'MB_WI' WIEN AACI END AS MB_WI,
    CASE WHEN Region = 'MN_WI' WIEN AACI END AS MN_WI,
    CASE WHEN Region = 'RN_WI' WIEN AACI END AS RN_WI,
    CASE WHEN Region = 'RS_WI' WIEN AACI END AS RS_WI,
    CASE WHEN Region = 'SE_WI' WIEN AACI END AS SE_WI,
    CASE WHEN Region = 'ST_WI' WIEN AACI END AS ST_WI,
    CASE WHEN Region = 'SV_WI' WIEN AACI END AS SV_WI,
    CASE WHEN Region = 'SW_WI' WIEN AACI END AS SW_WI,
    CASE WHEN Region = 'WT_WI' WIEN AACI END AS WT_WI
  FROM grouped
)
SELECT Year,
    --ALL
      SUM(AU_ALL) AS AU_ALL,
      SUM(CS_ALL) AS CS_ALL,
      SUM(EN_ALL) AS EN_ALL,
      SUM(ES_ALL) AS ES_ALL,
      SUM(MB_ALL) AS MB_ALL,
      SUM(MN_ALL) AS MN_ALL,
      SUM(RN_ALL) AS RN_ALL,
      SUM(RS_ALL) AS RS_ALL,
      SUM(SE_ALL) AS SE_ALL,
      SUM(ST_ALL) AS ST_ALL,
      SUM(SV_ALL) AS SV_ALL,
      SUM(SW_ALL) AS SW_ALL,
      SUM(WT_ALL) AS WT_ALL,
    --CDD
      SUM(AU_CDD) AS AU_CDD,
      SUM(CS_CDD) AS CS_CDD,
      SUM(EN_CDD) AS EN_CDD,
      SUM(ES_CDD) AS ES_CDD,
      SUM(MB_CDD) AS MB_CDD,
      SUM(MN_CDD) AS MN_CDD,
      SUM(RN_CDD) AS RN_CDD,
      SUM(RS_CDD) AS RS_CDD,
      SUM(SE_CDD) AS SE_CDD,
      SUM(ST_CDD) AS ST_CDD,
      SUM(SV_CDD) AS SV_CDD,
      SUM(SW_CDD) AS SW_CDD,
      SUM(WT_CDD) AS WT_CDD,
    --RAINFALL
      SUM(AU_RF) AS AU_RF,
      SUM(CS_RF) AS CS_RF,
      SUM(EN_RF) AS EN_RF,
      SUM(ES_RF) AS ES_RF,
      SUM(MB_RF) AS MB_RF,
      SUM(MN_RF) AS MN_RF,
      SUM(RN_RF) AS RN_RF,
      SUM(RS_RF) AS RS_RF,
      SUM(SE_RF) AS SE_RF,
      SUM(ST_RF) AS ST_RF,
      SUM(SV_RF) AS SV_RF,
      SUM(SW_RF) AS SW_RF,
      SUM(WT_RF) AS WT_RF,
    --SEALEVEL
      SUM(AU_SL) AS AU_SL,
      SUM(CS_SL) AS CS_SL,
      SUM(EN_SL) AS EN_SL,
      SUM(ES_SL) AS ES_SL,
      SUM(MB_SL) AS MB_SL,
      SUM(MN_SL) AS MN_SL,
      SUM(RN_SL) AS RN_SL,
      SUM(RS_SL) AS RS_SL,
      SUM(SE_SL) AS SE_SL,
      SUM(ST_SL) AS ST_SL,
      SUM(SV_SL) AS SV_SL,
      SUM(SW_SL) AS SW_SL,
      SUM(WT_SL) AS WT_SL,
    --TEMPHIGH
      SUM(AU_TH) AS AU_TH,
      SUM(CS_TH) AS CS_TH,
      SUM(EN_TH) AS EN_TH,
      SUM(ES_TH) AS ES_TH,
      SUM(MB_TH) AS MB_TH,
      SUM(MN_TH) AS MN_TH,
      SUM(RN_TH) AS RN_TH,
      SUM(RS_TH) AS RS_TH,
      SUM(SE_TH) AS SE_TH,
      SUM(ST_TH) AS ST_TH,
      SUM(SV_TH) AS SV_TH,
      SUM(SW_TH) AS SW_TH,
      SUM(WT_TH) AS WT_TH,
    --TEMPLOW
      SUM(AU_TL) AS AU_TL,
      SUM(CS_TL) AS CS_TL,
      SUM(EN_TL) AS EN_TL,
      SUM(ES_TL) AS ES_TL,
      SUM(MB_TL) AS MB_TL,
      SUM(MN_TL) AS MN_TL,
      SUM(RN_TL) AS RN_TL,
      SUM(RS_TL) AS RS_TL,
      SUM(SE_TL) AS SE_TL,
      SUM(ST_TL) AS ST_TL,
      SUM(SV_TL) AS SV_TL,
      SUM(SW_TL) AS SW_TL,
      SUM(WT_TL) AS WT_TL,
    --WIND
      SUM(AU_WI) AS AU_WI,
      SUM(CS_WI) AS CS_WI,
      SUM(EN_WI) AS EN_WI,
      SUM(ES_WI) AS ES_WI,
      SUM(MB_WI) AS MB_WI,
      SUM(MN_WI) AS MN_WI,
      SUM(RN_WI) AS RN_WI,
      SUM(RS_WI) AS RS_WI,
      SUM(SE_WI) AS SE_WI,
      SUM(ST_WI) AS ST_WI,
      SUM(SV_WI) AS SV_WI,
      SUM(SW_WI) AS SW_WI,
      SUM(WT_WI) AS WT_WI
FROM transposed
GROUP BY Year
;